global:
  enabled: true
  name: consul
  image: hashicorp/consul-enterprise:1.17-ent
  datacenter: dc1

  tls:
    enabled: true

  acls:
    manageSystemACLs: true

  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"

  enterpriseLicense:
    secretName: 'consul-ent-license'
    secretKey: 'key'

  imageConsulDataplane: hashicorp/consul-dataplane:1.3

server:
  enabled: true

ui:
  enabled: true
  service:
    type: NodePort

connectInject:
  enabled: true
  metrics:
    defaultEnableMerging: true
