---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - name: websocket
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
  namespace: default
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: server
  namespace: default
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: server
      app: server
  template:
    metadata:
      labels:
        service: server
        app: server
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "client:8001"
    spec:
      serviceAccountName: server
      containers:
        - name: server
          image: localhost:5001/lua-tracing-poc-server:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: ZIPKIN_HTTP_URL
              value: "http://jaeger-agent.observability.svc.cluster.local:9411/api/v2/spans"
